project:
  name: "haqei-analyzer"
  description: "HAQEI Analyzer + Serena MCP 設定"
  context: "haqei-development"
  architecture: "triple_os"

serena:
  modes: ["interactive", "editing", "planning"]
  tools:
    enabled:
      - file_tools
      - symbol_tools
      - memory_tools
      - config_tools
      - workflow_tools
  logging:
    # .serena に記録を残すルール
    activity_log: ".serena/activity.ndjson"
    policy:
      - on: "git-commit"
        action: "append-entry"
      - on: "deploy"
        action: "append-entry"
      - on: "future-simulator.analysis"
        action: "append-entry"
    redaction:
      remove_keys: ["apiKey", "token", "password"]

